service: treasure-functions
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  stage: prod
  region: us-east-1
  runtime: nodejs20.x
  environment:
    COINGECKO_API_KEY: ${env:COINGECKO_API_KEY}
    GOLDSKY_PROJECT_ID: ${env:GOLDSKY_PROJECT_ID}
    THIRDWEB_CLIENT_ID: ${env:THIRDWEB_CLIENT_ID}
    TROVE_API_KEY: ${env:TROVE_API_KEY}

package:
  individually: true

functions:
  # /magic
  getMagicTotalSupply:
    handler: src/handlers/magic.getTotalSupply
    events:
      - httpApi:
          path: /magic/total-supply
          method: get
      - httpApi:
          path: /total-supply
          method: get
  getMagicCirculatingSupply:
    handler: src/handlers/magic.getCirculatingSupply
    events:
      - httpApi:
          path: /magic/circulating-supply
          method: get
      - httpApi:
          path: /circulating-supply
          method: get
  getMagicPrice:
    handler: src/handlers/magic.getPrice
    events:
      - httpApi:
          path: /magic/price
          method: get
  getMagicWethSlpPrice:
    handler: src/handlers/magic.getMagicWethSlpPrice
    events:
      - httpApi:
          path: /magic/slp
          method: get
  getMagicExchangeInfo:
    handler: src/handlers/magic.getMagicExchangeInfo
    events:
      - httpApi:
          path: /magic/exchange-info
          method: get
      - httpApi:
          path: /upbit-feed
          method: get
  # /bridgeworld
  getCorruption:
    handler: src/handlers/bridgeworld.getCorruption
    events:
      - httpApi:
          path: /bridgeworld/corruption
          method: get
  getMines:
    handler: src/handlers/bridgeworld.getMines
    events:
      - httpApi:
          path: /mines
          method: get
      - httpApi:
          path: /bridgeworld/mines
          method: get
  getLegionHolders:
    handler: src/handlers/bridgeworld.getLegionHolders
  verifyGenesisLegionHolders:
    handler: src/handlers/bridgeworld.verifyGenesisLegionHolders
    events:
      - httpApi:
          path: /bridgeworld/legions/verify
          method: post
  verifyHarvesterAccess:
    handler: src/handlers/bridgeworld.verifyHarvesterAccess
    events:
      - httpApi:
          path: /bridgeworld/harvesters/{id}/verify
          method: post
  # /beacon
  verifyBeaconHolders:
    handler: src/handlers/beacon.verifyBeaconHolders
    events:
      - httpApi:
          path: /beacon/verify
          method: post
  verifyFoundingCharacterHolders:
    handler: src/handlers/beacon.verifyFoundingCharacterHolders
    events:
      - httpApi:
          path: /beacon/founding-characters/verify
          method: post
  verifyPetHolders:
    handler: src/handlers/beacon.verifyPetHolders
    events:
      - httpApi:
          path: /beacon/pets/verify
          method: post
  verifyWritOfPassageHolders:
    handler: src/handlers/beacon.verifyWritOfPassageHolders
    events:
      - httpApi:
          path: /beacon/writ-of-passage/verify
          method: post
