name: PR Checks
on: pull_request
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Check types
        run: npm run typecheck
      - name: Test
        run: npm test
